### ISSUE TITLE
This is not working on ionic 4

### ISSUE THREAD

**Issue by saikatkoley** [aggarwalankush/ionic2-mosum#12]
I have just tried to install this app with ionic 4 but showing lots of error.

"C:\ionicproject\mosum\node_modules\node-sass\build\binding.sln" (default target) (1) ->
"C:\ionicproject\mosum\node_modules\node-sass\build\binding.vcxproj.metaproj" (default target) (2) ->
"C:\ionicproject\mosum\node_modules\node-sass\build\binding.vcxproj" (default target) (4) ->
(ClCompile target) ->
  c:\ionicproject\mosum\node_modules\nan\nan_maybe_43_inl.h(112): error C2039: 'ForceSet': is not a member of 'v8::Object' (compiling source file ..
\src\binding.cpp)c:\ionicproject\mosum\node_modules\nan\nan_maybe_43_inl.h(112): error C2039: 'ForceSet': is not a member of 'v8::Object' (compiling
 source file ..\src\create_string.cpp) [C:\ionicproject\mosum\node_modules\node-sass\build\binding.vcxproj]
  c:\ionicproject\mosum\node_modules\nan\nan_maybe_43_inl.h(112): error C2039: 'ForceSet': is not a member of 'v8::Object' (compiling source file ..
\src\custom_function_bridge.cpp) [C:\ionicproject\mosum\node_modules\node-sass\build\binding.vcxproj]
  c:\ionicproject\mosum\node_modules\nan\nan_maybe_43_inl.h(112): error C2039: 'ForceSet': is not a member of 'v8::Object' (compiling source file ..
\src\custom_importer_bridge.cpp) [C:\ionicproject\mosum\node_modules\node-sass\build\binding.vcxproj]
  c:\ionicproject\mosum\node_modules\nan\nan_maybe_43_inl.h(112): error C2039: 'ForceSet': is not a member of 'v8::Object' (compiling source file ..
\src\sass_context_wrapper.cpp) [C:\ionicproject\mosum\node_modules\node-sass\build\binding.vcxproj]
  c:\ionicproject\mosum\node_modules\nan\nan_maybe_43_inl.h(112): error C2039: 'ForceSet': is not a member of 'v8::Object' (compiling source file ..
\src\sass_types\boolean.cpp) [C:\ionicproject\mosum\node_modules\node-sass\build\binding.vcxproj]
  c:\ionicproject\mosum\node_modules\nan\nan_maybe_43_inl.h(112): error C2039: 'ForceSet': is not a member of 'v8::Object' (compiling source file ..
\src\sass_types\color.cpp) [C:\ionicproject\mosum\node_modules\node-sass\build\binding.vcxproj]
  c:\ionicproject\mosum\node_modules\nan\nan_maybe_43_inl.h(112): error C2039: 'ForceSet': is not a member of 'v8::Object' (compiling source file ..
\src\sass_types\factory.cpp) [C:\ionicproject\mosum\node_modules\node-sass\build\binding.vcxproj]
  c:\ionicproject\mosum\node_modules\nan\nan_maybe_43_inl.h(112): error C2039: 'ForceSet': is not a member of 'v8::Object' (compiling source file ..
\src\sass_types\list.cpp) [C:\ionicproject\mosum\node_modules\node-sass\build\binding.vcxproj]
  c:\ionicproject\mosum\node_modules\nan\nan_maybe_43_inl.h(112): error C2039: 'ForceSet': is not a member of 'v8::Object' (compiling source file ..
\src\sass_types\map.cpp) [C:\ionicproject\mosum\node_modules\node-sass\build\binding.vcxproj]
  c:\ionicproject\mosum\node_modules\nan\nan_maybe_43_inl.h(112): error C2039: 'ForceSet': is not a member of 'v8::Object' (compiling source file ..
\src\sass_types\null.cpp) [C:\ionicproject\mosum\node_modules\node-sass\build\binding.vcxproj]
  c:\ionicproject\mosum\node_modules\nan\nan_maybe_43_inl.h(112): error C2039: 'ForceSet': is not a member of 'v8::Object' (compiling source file ..
\src\sass_types\number.cpp) [C:\ionicproject\mosum\node_modules\node-sass\build\binding.vcxproj]
  c:\ionicproject\mosum\node_modules\nan\nan_maybe_43_inl.h(112): error C2039: 'ForceSet': is not a member of 'v8::Object' (compiling source file ..
\src\sass_types\string.cpp) [C:\ionicproject\mosum\node_modules\node-sass\build\binding.vcxproj]

    97 Warning(s)
    12 Error(s)

Time Elapsed 00:02:12.41
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\ionicproject\mosum\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:197:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\ionicproject\\mosum\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\ionicproject\mosum\node_modules\node-sass
gyp ERR! node -v v11.9.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.5.3 (node_modules\node-sass):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.5.3 postinstall: `node scripts/build.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

added 1 package from 1 contributor and audited 3110 packages in 230.234s
found 79 vulnerabilities (32 low, 34 moderate, 13 high)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by aggarwalankush** [comment]
Yes, it's not updated to Ionic 4. It will be great if someone can add a PR
